name: Test

on:
  pull_request:
    types: [opened, reopened]
  push:
    branches:
      - master
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Check code formatting
        run: cargo fmt --all -- --check

      - name: Test code
        run: cargo test --verbose --all
